routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('coming-soon');
});

Route::get('/privacy-policy', function () {
    return view('privacy-policy');
});
Route::get('/terms-of-service', function () {
    return view('terms-of-service');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', 'AdminController@index')->name('admin.dashboard');
Route::get('/admin/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('/admin/login','Auth\AdminLoginController@login')->name('admin.login.submit');
Route::get('/artists/getdata','ArtistController@getdata')->name('artists.getdata');
Route::get('/artists/search','ArtistController@search')->name('artists.search');
Route::resource('artists', 'ArtistController');
Route::get('/gigs/getdata','GigController@getdata')->name('gigs.getdata');
Route::resource('gigs', 'GigController');
Route::get('/users/getdata','UserController@getData')->name('users.getdata');
Route::resource('users','UserController');

resources/views/admin-artist-create-form.blade.php
@extends('layouts.admin-flip')
@section('content')
<style>
  img {
    max-width: 100%; /* This rule is very important, please do not ignore this! */
  }
</style>
<div class="col-md-6">
      <div class="box">
        <div class="box-header">
          <h2>Add Artist</h2>
        </div>
        <div class="box-divider m-0"></div>
        <div class="box-body">
          <form role="form" method="post" action="{{ route('artists.store') }}" id="form" enctype="multipart/form-data"  >
            {{ csrf_field() }}
            <div class="form-group row">
              <label for="name" class="col-sm-2 form-control-label">Name</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name='name' placeholder="Name">
              </div>
            </div>
            <div class="form-group row">
              <label for="bioindo" class="col-sm-2 form-control-label">Bio. Indo</label>
              <div class="col-sm-10">
                <textarea class="form-control" rows="2" name='bioindo' placeholder="Say what you say ..."></textarea>
              </div>
            </div>
            <div class="form-group row">
              <label for="bioenglish" class="col-sm-2 form-control-label">Bio. English</label>
              <div class="col-sm-10">
                <textarea class="form-control" rows="2" name='bioenglish' placeholder="Say what you say ..."></textarea>
              </div>
            </div>
            <div class="form-group row">
              <label for="photo_profile" class="col-sm-2 form-control-label">Photo Profile</label>
              <div class="col-sm-10">
                <input type="button" name="btn" value="Upload" id="uploadPflBtn" class="btn" />
              </br>
                <img id="photoProfile" width="150">
                <input type="hidden"  id="photoProfileImg" name="photo_profile">
              </div>
            </div>
            <div class="form-group row">
              <label for="photo_cover" class="col-sm-2 form-control-label">Photo Cover</label>
              <div class="col-sm-10">
                <input type="button" name="btn" value="Upload" id="uploadCvrBtn" class="btn" />
              </br>
                <img id="photoCover" width="150">
                <input type="hidden"  id="photoCoverImg" name="photo_cover">
              </div>
            </div>
            <div class="form-group row">
              <label for="email" class="col-sm-2 form-control-label">Email</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name='email' placeholder="Email">
              </div>
            </div>
            <div class="form-group row">
              <label for="phone" class="col-sm-2 form-control-label">Phone</label>
              <div class="col-sm-10">
                <input type="number" class="form-control" name='phone' placeholder="Phone">
              </div>
            </div>
            <div class="form-group row">
              <label for="instagram" class="col-sm-2 form-control-label">Instagram</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name='instagram' placeholder="Instagram">
              </div>
            </div>
            <div class="form-group row">
              <label for="twitter" class="col-sm-2 form-control-label">Twitter</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name='twitter' placeholder="Twitter">
              </div>
            </div>
            <div class="form-group row">
              <label for="facebook" class="col-sm-2 form-control-label">Facebook</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name='facebook' placeholder="Facebook">
              </div>
            </div>
            <div class="form-group row">
              <label for="soundcloud" class="col-sm-2 form-control-label">Soundcloud</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name='soundcloud' placeholder="Soundcloud">
              </div>
            </div>
            <div class="form-group row">
              <label for="bandcamp" class="col-sm-2 form-control-label">Bandcamp</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name='bandcamp' placeholder="Bandcamp">
              </div>
            </div>
            <div class="form-group row">
              <label for="reverbnation" class="col-sm-2 form-control-label">Reverbnation</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name='reverbnation' placeholder="Reverbnation">
              </div>
            </div>
            <div class="form-group row">
              <label for="youtube" class="col-sm-2 form-control-label">Youtube</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name='youtube' placeholder="Youtube">
              </div>
            </div>
            <div class="form-group row">
              <label for="spotify" class="col-sm-2 form-control-label">Spotify</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name='spotify' placeholder="Spotify">
              </div>
            </div>
            <div class="form-group row">
              <label for="website" class="col-sm-2 form-control-label">Website</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name='website' placeholder="Website">
              </div>
            </div>
            <div class="form-group row">
              <label for="artists" class="col-sm-2 form-control-label">Publish</label>
              <div class="col-sm-10">
                <div class="form-control">
                <label class="ui-check col-sm-2">
                  <input type="checkbox" id="publish" name="is_published"><i></i> YES
                </label>
                </div>
              </div>
            </div>
            <div class="form-group row m-t-md">
              <div class="col-sm-offset-2 col-sm-12">
                <input type="button" name="btn" value="Submit" id="submitBtn" data-toggle="modal" data-target="#confirm-submit" class="btn btn-primary pull-right" />
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
@include('layouts.modal-submit')
@include('layouts.modal-image-upload')
@push('scripts')
  <script>
  $('#uploadPflBtn').click(function(){
    if(cropper!=""){
      cropper.destroy();
    }
    cropper = new Cropper(image, {
      aspectRatio: 1 / 1,
    });
    idPhoto = "photoProfile";
    idPhotoData = "photoProfileImg";
    $('#upload-image').modal('toggle');
  });
  $('#uploadCvrBtn').click(function(){
    if(cropper!=""){
      cropper.destroy();
    }
    cropper = new Cropper(image, {
      aspectRatio: 4 / 3,
    });
    idPhoto = "photoCover";
    idPhotoData = "photoCoverImg";
    $('#upload-image').modal('toggle');
  });
  </script>
@endpush
@endsection

resources/views/admin-artist-edit-form.blade.php
@extends('layouts.admin-flip')
@section('content')
    <style>
        img {
            max-width: 100%; /* This rule is very important, please do not ignore this! */
        }
    </style>
    <div class="col-md-6">
        <div class="box">
            <div class="box-header">
                <h2>Add Artist</h2>
            </div>
            <div class="box-divider m-0"></div>
            <div class="box-body">
                <form role="form" method="post" action="{{ route('artists.update',$artist->id) }}" id="form"
                      enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="put"/>
                    <div class="form-group row">
                        <label for="name" class="col-sm-2 form-control-label">Name</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name='name' placeholder="Name"
                                   value="{{$artist->name}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="bioindo" class="col-sm-2 form-control-label">Bio. Indo</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" rows="2" name='bioindo'
                                      placeholder="Say what you say ...">{{$artist->bio_indo}}</textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="bioenglish" class="col-sm-2 form-control-label">Bio. English</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" rows="2" name='bioenglish'
                                      placeholder="Say what you say ...">{{$artist->bio_english}}</textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="photo_profile" class="col-sm-2 form-control-label">Photo Profile</label>
                        <div class="col-sm-10">
                            <input type="button" name="btn" value="Upload" id="uploadPflBtn" class="btn"/>
                            </br>
                            <img id="photoProfile" src="{{config('constants.aws_prefix')}}{{ $artist->photo_profile}}"
                                 width="150">
                            <input type="hidden" id="photoProfileImg" name="photo_profile">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="photo_cover" class="col-sm-2 form-control-label">Photo Cover</label>
                        <div class="col-sm-10">
                            <input type="button" name="btn" value="Upload" id="uploadCvrBtn" class="btn"/>
                            </br>
                            <img id="photoCover" src="{{config('constants.aws_prefix')}}{{ $artist->photo_cover}}"
                                 width="150">
                            <input type="hidden" id="photoCoverImg" name="photo_cover">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="email" class="col-sm-2 form-control-label">Email</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name='email' placeholder="Email"
                                   value="{{$artist->email}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="phone" class="col-sm-2 form-control-label">Phone</label>
                        <div class="col-sm-10">
                            <input type="number" class="form-control" name='phone' placeholder="Phone"
                                   value="{{$artist->phone}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="instagram" class="col-sm-2 form-control-label">Instagram</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name='instagram' placeholder="Instagram"
                                   value="{{$artist->instagram}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="twitter" class="col-sm-2 form-control-label">Twitter</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name='twitter' placeholder="Twitter"
                                   value="{{$artist->twitter}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="facebook" class="col-sm-2 form-control-label">Facebook</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name='facebook' placeholder="Facebook"
                                   value="{{$artist->facebook}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="soundcloud" class="col-sm-2 form-control-label">Soundcloud</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name='soundcloud' placeholder="Soundcloud"
                                   value="{{$artist->soundcloud}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="bandcamp" class="col-sm-2 form-control-label">Bandcamp</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name='bandcamp' placeholder="Bandcamp"
                                   value="{{$artist->bandcamp}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="reverbnation" class="col-sm-2 form-control-label">Reverbnation</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name='reverbnation' placeholder="Reverbnation"
                                   value="{{$artist->reverbnation}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="youtube" class="col-sm-2 form-control-label">Youtube</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name='youtube' placeholder="Youtube"
                                   value="{{$artist->youtube}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="spotify" class="col-sm-2 form-control-label">Spotify</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name='spotify' placeholder="Spotify"
                                   value="{{$artist->spotify}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="website" class="col-sm-2 form-control-label">Website</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" name='website' placeholder="Website"
                                   value="{{$artist->website}}">
                        </div>
                    </div>
                    <div class="form-group row">
                      <label for="artists" class="col-sm-2 form-control-label">Publish</label>
                      <div class="col-sm-10">
                        <div class="form-control">
                        <label class="ui-check col-sm-2">
                          <input type="checkbox" id="publish" name="is_published" {{($artist->is_published==1) ? 'checked':''}}><i></i> YES
                        </label>
                        </div>
                      </div>
                    </div>
                    <div class="form-group row m-t-md">
                        <div class="col-sm-offset-2 col-sm-12">
                            <input type="button" name="btn" value="Submit" id="submitBtn" data-toggle="modal"
                                   data-target="#confirm-submit" class="btn btn-primary pull-right"/>
                            <input type="button" name="btn" value="Delete" id="deleteBtn" data-toggle="modal" data-target="#confirm-delete" class="btn btn-warning" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    @include('layouts.modal-submit')
    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    Confirm Submit
                </div>
                <div class="modal-body">
                    Are you sure to delete ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <a href="#" data-method="delete" id="delete" class="btn btn-success success">Submit</a>
                </div>
            </div>
        </div>
    </div>
    @include('layouts.modal-image-upload')
    @push('scripts')
        <script>
            $('#uploadPflBtn').click(function () {
                if (cropper != "") {
                    cropper.destroy();
                }
                cropper = new Cropper(image, {
                    aspectRatio: 1 / 1,
                });
                idPhoto = "photoProfile";
                idPhotoData = "photoProfileImg";
                $('#upload-image').modal('toggle');
            });
            $('#uploadCvrBtn').click(function () {
                if (cropper != "") {
                    cropper.destroy();
                }
                cropper = new Cropper(image, {
                    aspectRatio: 4 / 3,
                });
                idPhoto = "photoCover";
                idPhotoData = "photoCoverImg";
                $('#upload-image').modal('toggle');
            });
            //delete
            $('#delete').click(function(){
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });

                $.ajax({
                    type: 'delete',
                    url: '{{ route('artists.destroy',$artist->id) }}'
                }).done(function (data) {
                    window.location = '{{ route('artists.index') }}';
                });
            });
        </script>
    @endpush
@endsection

resources/views/admin-artist-list.blade.php
@extends('layouts.admin-flip')
@section('content')
<!-- ############ PAGE START-->
<div class="padding">
  <div class="box">
    <div class="box-header">
      <h2>Project List</h2>
    </div>
    <div class="table-responsive">
      <table ui-jp="dataTable" id="users-table"
          ui-options="{
              sAjaxSource: '{!! route('artists.getdata') !!}',
              aoColumns: [
                { mData: 'id' },
                { mData: 'name' },
                { mData: 'email' },
                { mData: 'is_published'},
                {
				           mData: 'id',
				           mRender: function(data) {
                     var url = '<a class=btn  href={{ route('artists.edit', ':id') }}>Details</a>';
                     url = url.replace(':id',data);
                     return url;
				         }
			          }
              ]}"
          class="table table-striped b-t b-b">
        <thead>
          <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Publish</th>
            <th>Details</th>
          </tr>
        </thead>

      </table>
    </div>
  </div>
</div>

@endsection

resources/views/admin-gig-list.blade.php
@extends('layouts.admin-flip')
@section('content')
<!-- ############ PAGE START-->
<div class="padding">
  <div class="box">
    <div class="box-header">
      <h2>Project List</h2>
    </div>
    <div class="table-responsive">
      <table ui-jp="dataTable" id="users-table"
          ui-options="{
              sAjaxSource: '{!! route('gigs.getdata') !!}',
              aoColumns: [
                { mData: 'id' },
                { mData: 'name' },
                { mData: 'place' },
                { mData: 'event_date' },
                { mData: 'is_gigs_slider'},
                { mData: 'is_published'},
                {
				           mData: 'id',
				           mRender: function(data) {
                     var url = '<a class=btn  href={{ route('gigs.edit', ':id') }}>Details</a>';
                     url = url.replace(':id',data);
                     return url;
				         }
			          }
              ]}"
          class="table table-striped b-t b-b">
        <thead>
          <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Place</th>
            <th>Event Date</th>
            <th>Gigs Slider</th>
            <th>Publish</th>
            <th>Details</th>
          </tr>
        </thead>

      </table>
    </div>
  </div>
</div>

@endsection

resources/views/admin-user-edit-form.blade.php
@extends('layouts.admin-flip')
@section('content')
<style>
      .controls {
        margin-top: 10px;
        border: 1px solid transparent;
        border-radius: 2px 0 0 2px;
        box-sizing: border-box;
        -moz-box-sizing: border-box;
        height: 32px;
        outline: none;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
      }
      #pac-input {
        background-color: #fff;
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
        margin-left: 12px;
        padding: 0 11px 0 13px;
        text-overflow: ellipsis;
        width: 300px;
      }

    #pac-input:focus {
      border-color: #4d90fe;
    }

    .pac-container {
      font-family: Roboto;
    }
    img {
      max-width: 100%; /* This rule is very important, please do not ignore this! */
    }
</style>
<div class="col-md-6">
      <div class="box">
        <div class="box-header">
          <h2>Edit User</h2>
        </div>
        <div class="box-divider m-0"></div>
        <div class="box-body">
          <form role="form" method="post" action="{{ route('users.update',$user->id) }}" id="form" enctype="multipart/form-data"  >
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="put" />
            <div class="form-group row">
              <label for="name" class="col-sm-2 form-control-label">Name</label>
              <div class="col-sm-10">
                <input type="text" class="form-control" name='name' placeholder="Name" value="{{$user->name}}">
              </div>
            </div>
            <div class="form-group row">
              <label for="description" class="col-sm-2 form-control-label">Email</label>
              <div class="col-sm-10">
                  <input type="text" readonly class="form-control" name='email' placeholder="Email" value="{{$user->email}}">
              </div>
            </div>
            <div class="form-group row m-t-md">
              <div class="col-sm-offset-2 col-sm-12">
                <input type="button" name="btn" value="Submit" id="submitBtn" data-toggle="modal" data-target="#confirm-submit" class="btn btn-primary pull-right" />
                <input type="button" name="btn" value="Delete" id="deleteBtn" data-toggle="modal" data-target="#confirm-delete" class="btn btn-warning" />
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
    <!--bootstrap modal-->
    <div class="modal fade" id="confirm-submit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  Confirm Submit
              </div>
              <div class="modal-body">
                  Are you sure to submit ?
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <a href="#" id="submit" class="btn btn-success success">Submit</a>
              </div>
          </div>
      </div>
    </div>

    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  Confirm Submit
              </div>
              <div class="modal-body">
                  Are you sure to delete ?
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <a href="#" data-method="delete" id="delete" class="btn btn-success success">Submit</a>
              </div>
          </div>
      </div>
    </div>
    <!--end bootstrap modal-->

@include('layouts.modal-submit')
@push('scripts')
  <script type="text/javascript">

  $('#delete').click(function(){
    alert('test');
    $.ajaxSetup({
      headers: {
          'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      }
    });

    var $this = $(this);
    $.ajax({
        type: 'delete',
        url: '{{ route('users.destroy',$user->id) }}'
    }).done(function (data) {
      window.location = '{{ route('users.index') }}';
    });
  });
  </script>
@endpush
@endsection

resources/views/admin-user-list.blade.php
@extends('layouts.admin-flip')
@section('content')
<!-- ############ PAGE START-->
<div class="padding">
  <div class="box">
    <div class="box-header">
      <h2>Project List</h2>
    </div>
    <div class="table-responsive">
      <table ui-jp="dataTable" id="users-table"
          ui-options="{
              sAjaxSource: '{!! route('users.getdata') !!}',
              aoColumns: [
                { mData: 'id' },
                { mData: 'name' },
                { mData: 'email' },
                {
				           mData: 'id',
				           mRender: function(data) {
                     var url = '<a class=btn  href={{ route('users.edit', ':id') }}>Details</a>';
                     url = url.replace(':id',data);
                     return url;
				         }
			          }
              ]}"
          class="table table-striped b-t b-b">
        <thead>
          <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Provider</th>
          </tr>
        </thead>

      </table>
    </div>
  </div>
</div>

@endsection

resources/views/admin.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in as ADMIN!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection